---
named_interfaces::config:
  mgmt:
    - br0
  transport:
    - em1
    - em2

foreman_bootstrap::virt_install:
  osl-foreman-01:
    domain:          'iaas.uio.no'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '129.240.224.101'
    install_netmask: '255.255.255.224'
    install_gateway: '129.240.224.97'
