---
include:
  default:
    - profile::network::services

named_interfaces::config:
  mgmt:
    - br0
  transport:
    - em1
    - em2

foreman_bootstrap::virt_install:
  osl-foreman-01:
    domain:          'iaas.uio.no'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '172.16.32.11'
    install_netmask: '255.255.248.0'
    install_gateway: '172.16.32.12'

profile::network::services::ntp_server: true
