---
profile::network::services::manage_dhcp: false

foreman_bootstrap::tftp_install:
  osl-controller-01:
    domain:           'iaas.uio.no'
    dhcp_interface:   'em1'
    dhcp_range_start: '129.240.224.118'
    dhcp_range_end:   '129.240.224.126'
    dhcp_gateway:     '129.240.224.97'

openstack_extras::repo::redhat::redhat::purge_unmanaged: false

openstack_extras::repo::redhat::redhat::repo_hash:
  'epel':
    'descr': "Extra Packages for Enterprise Linux %{operatingsystemmajrelease} - $basearch"
    'baseurl': "%{hiera('yum_epel_mirror')}/%{operatingsystemmajrelease}/$basearch/"
    'gpgkey': 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7'
    'failovermethod': 'priority'
  'puppetlabs':
    'descr': Puppetlabs Yum Repo
    'baseurl':  'http://yum.puppetlabs.com/el/$releasever/products/$basearch/'
    'gpgkey':   'http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs'
    'gpgcheck': 1
  'puppetlabs-deps':
    'descr': Puppetlabs Dependencies Yum Repo
    'baseurl':  'http://yum.puppetlabs.com/el/$releasever/dependencies/$basearch/'
    'gpgkey':   'http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs'
    'gpgcheck': 1
openstack_extras::repo::redhat::redhat::gpgkey_hash:
  '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7':
    'source': 'puppet:///modules/openstack_extras/RPM-GPG-KEY-EPEL-7'

