---
profile::network::services::manage_dhcp: false

foreman_bootstrap::tftp_install:
  osl-controller-1:
    domain:           'iaas.uio.no'
    dhcp_interface:   'em1'
    dhcp_range_start: '129.240.224.118'
    dhcp_range_end:   '129.240.224.126'
    dhcp_gateway:     '129.240.224.97'

