---
include:
  default:
    - profile::storage::cephmon
    - profile::storage::cephmon_firewall
  firstboot:
    - profile::storage::cephmon_firewall

profile::storage::cephmon_firewall::manage_firewall:  true

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present
