---
include:
  default:
    - profile::openstack::compute::hypervisor
    - profile::openstack::volume
    - profile::openstack::network

openstack_extras::repo::redhat::redhat::manage_rdo: false
profile::base::common::manage_lvm: true

profile::openstack::network::l2_driver: calico
profile::base::common::common_packages:
  - python-etcd
  - python-posix-spawn

calico::compute: true
bird::config_template_v4: calico/compute/bird.conf.erb

etcd::initial_cluster: ["%{hiera('service__address__etcd_cluster')}"]
etcd::mode: 'proxy'

mgmt_interface: 'em3'
mgmt_address:   "%{ipaddress_em3}"

lvm::logical_volume:
  lv_instances:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/nova/instances

sudo::purge: false

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present
