---
include:
  default:
    - profile::openstack::compute::hypervisor
    - profile::openstack::volume
    - profile::openstack::network
  bootstrap:
    - profile::base::lvm

openstack_extras::repo::redhat::redhat::manage_rdo: false
profile::base::common::manage_lvm: true

profile::openstack::network::l2_driver: calico
profile::base::common::common_packages:
  - python-etcd
  - python-posix-spawn

calico::compute: true
etcd::mode: 'proxy'

named_interfaces::config:
  mgmt:
    - em3

sudo::purge: false

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present

profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - '/dev/sda3'

lvm::volume_groups:
  'vg_ext':
    physical_volumes:
      - '/dev/sda3'
    logical_volumes:
      lv_instances:
        fs_type:   xfs
        mountpath: "/var/lib/nova/instances"
