---
classes:
   - profile::openstack::compute::hypervisor

openstack_extras::repo::redhat::redhat::manage_rdo: true
profile::base::common::manage_lvm: false

mgmt_interface: 'em3'
mgmt_address:   "%{ipaddress_em3}"

lvm::logical_volume:
  lv_var:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/ekstradisk

