---
classes:
  - profile::application::foreman
  - profile::database::postgresql
  - profile::webserver::apache
  - hostname
  - foreman::cli
  - foreman::compute::libvirt
  - foreman::plugin::hooks
  - foreman::plugin::discovery
  - foreman::plugin::templates
classes_bootstrap:
  - hostname

profile::application::foreman::manage_eyaml:    true
profile::application::foreman::manage_firewall: true

foreman::foreman_url:                       "https://%{fqdn}"
foreman::configure_epel_repo:               false
foreman::admin_username:                    'admin'
foreman::admin_password:                    'changeme'
foreman::admin_email:                       'admin@localhost.localdomain'
foreman::ssl:                               true
foreman::cli::manage_root_config:           true
foreman::plugin::discovery::install_images: true

foreman_proxy::log_level:            'DEBUG'
foreman_proxy::ssl:                  true
foreman_proxy::register_in_foreman:  true
foreman_proxy::manage_sudoersd:      false
foreman_proxy::tftp:                 true
foreman_prxoy::tftp_servername:      "%{ipaddress}"
foreman_proxy::dhcp:                 true
foreman_proxy::dhcp_interface:       'eth0'
foreman_proxy::dhcp_managed:         true
foreman_proxy::dns:                  true
foreman_proxy::dns_forwarders:       ['8.8.8.8']
foreman_proxy::dns_managed:          true
foreman_prxoy::dns_provider:         'nsupdate'
foreman_proxy::puppetrun:            true
foreman_proxy::puppetca:             true
foreman_proxy::bmc:                  true
foreman_proxy::bmc_default_provider: 'ipmitool'

puppet::server:                        true
puppet::server_foreman_url:            "https://%{fqdn}"
puppet::dns_alt_names:                 ["puppet.%{domain}","puppetca.%{domain}","admin.%{domain}"]
puppet::server_directory_environments: false
puppet::server_environments:           []
puppet::server_external_nodes:         ''

profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::vhost_definition:
  'files':
    servername:     "%{fqdn}"
    port:           80
    docroot:        '/opt/repo'
    docroot_owner:  'iaas'

dhcp::onie_inst_def_url:     "http://%{fqdn}/cumuluslinux/onie-installer-powerpc"
dhcp::cumulus_provision_url: "http://%{fqdn}/cumuluslinux/provision.sh"

