---
classes:
  - profile::base::login
  - profile::network::services
  - foreman_bootstrap::instances

profile::base::common::manage_firewall: false

accounts::accounts:
  '@admins':
    ensure: present
  'vagrant':
    ensure: absent
  'iaas':
    ensure: absent

ssh::server::options:
  # Need this for 2FA (saz-ssh-module disables by default)
  ChallengeResponseAuthentication: 'yes'
  # The second publickey is until the pam files are fixed
  AuthenticationMethods: 'publickey,keyboard-interactive:pam publickey'
  # Explicitly enable the required methods
  UsePAM: 'yes'
  PasswordAuthentication: 'yes'
  PubKeyAuthentication: 'yes'

googleauthenticator::pam::mode::modes:
  wheel-only:
    condition: 'user ingroup wheel'
    nullok: true

googleauthenticator::pam::modules:
  sshd:
    mode: wheel-only
