---
include:
  default:
    - profile::messaging::rabbitmq
    - profile::openstack::compute::api
    - profile::openstack::compute::scheduler
    - profile::openstack::compute::conductor
    - profile::openstack::compute::consoleauth
    - profile::openstack::compute::consoleproxy
    - profile::openstack::dashboard
    - profile::openstack::identity
    - profile::openstack::image::api
    - profile::openstack::image::registry
    - profile::openstack::volume
    - profile::openstack::volume::api
    - profile::openstack::volume::scheduler
    - profile::openstack::volume::storage
    - cinder::setup_test_volume
    - profile::openstack::network::controller
#    - profile::openstack::network::dhcp
#    - profile::openstack::network::l3
#    - profile::openstack::network::metadata
    - profile::application::etcd

profile::base::network::manage_dummy: true
profile::base::common::manage_lvm: false
profile::base::common::common_packages:
  - python-etcd

profile::application::sslcert::create_new: true
profile::application::sslcert::cert_defines:
  "%{fqdn}":
    country:      'NO'
    organization: 'private.org'
    commonname:   "%{fqdn}"
    owner:        apache

calico::controller: true
calico::reflector: true

openstack_extras::repo::redhat::redhat::manage_rdo: false

lvm::logical_volume:
  lv_var:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/ekstradisk

sudo::purge: false

apache::default_mods: false
apache::default_vhost: false
apache::default_confd_files: false

etcd::mode: cluster
etcd::node_name: 'master'

profile::openstack::network::policies:
  create_network:
    key:   'create_network'
    value: 'rule:admin_only'
  create_router:
    key:   'create_router'
    value: 'rule:admin_only'
