---
classes:
   - profile::database::mariadb

profile::database::mariadb::manage_repo: false
profile::base::common::manage_lvm: false

lvm::logical_volume:
  lv_var:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/ekstradisk


