---
include:
  default:
    - profile::storage::cephosd
    - profile::storage::cephpool
    - profile::storage::cephosd_firewall
    - profile::base::lvm
  kickstart:
    - profile::base::lvm
  bootstrap:
    - profile::base::lvm
    - profile::storage::cephosd_firewall

profile::base::manage_lvm:                           true

profile::storage::cephosd_firewall::manage_firewall: true

accounts::users:
  'cinder':
    ensure: present
  'glance':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'
  'glance':
    - 'glance'

accounts::accounts:
  'cinder':
    ensure: present
  'glance'
    ensure: present

ceph::profile::params::osd_journal_size: '10240'

profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
  'volumes':
    ensure: present
    pg_num: 1500
    pgp_num: 1500
  'images':
    ensure: present
    pg_num: 1500
    pgp_num: 1500
