---
include:
  default:
    - profile::storage::cephosd
    - profile::storage::cephpool
    - profile::storage::cephosd_firewall
    - profile::base::lvm
  kickstart:
    - profile::base::lvm
  bootstrap:
    - profile::base::lvm
    - profile::storage::cephosd_firewall

profile::base::manage_lvm:                           true

profile::storage::cephosd_firewall::manage_firewall: true

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present

profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
  'volumes':
    ensure: present
  'images':
    ensure: present
