---
include:
  default:
    - profile::storage::cephosd
    - profile::storage::cephpool
    - profile::storage::cephosd_firewall
    - profile::base::lvm
  bootstrap:
    - profile::storage::cephosd_firewall
    - profile::base::lvm

profile::base::manage_lvm:                           true

profile::storage::cephosd_firewall::manage_firewall: true

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present

ceph::profile::params::pools:
  'volumes':
     pg_num: 128
  'images':
     pg_num: 128
  'backups':
     pg_num: 128
  'vms':
     pg_num: 128
