---
# The current vagrant box image do not have vda3 parso switch
# off lvm for compute on vagrant
profile::base::common::manage_lvm: false

profile::base::lvm::physical_volume:
  '/dev/vda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/vda3

# consul testdata
include:
  default:
    - profile::application::consul

consul::services:
  'foreman':
    tags: ["TheForeman"]
    port: 80

