named_interfaces::config:
  mgmt:
     - eth0
  transport:
     - eth0_912
     - eth1

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true

ceph::profile::params::osds:
  '/dev/sda3':
    journal: '/journal/sda3'
