---
foreman_bootstrap::virt_install:
  bgo-foreman-1:
    domain:          'mgmt.iaas.intern'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '172.16.32.11'
    install_netmask: '255.255.248.0'
    install_gateway: '172.16.32.1'
