---
foreman_bootstrap::virt_install:
  bgo-foreman-1:
    domain:          'mgmt.iaas.intern'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '172.16.32.11'
    install_netmask: '255.255.248.0'
    install_gateway: '172.16.32.1'
  dev01-foreman-01:
    domain:          'mgmt.dev.iaas.intern'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '192.168.10.11'
    install_netmask: '255.255.255.0'
    install_gateway: '192.168.10.1'
