---
named_interfaces::config:
  mgmt:
     - eth0
  transport:
     - eth1
  public:
     - dummy0

# NOTE: reflectors will be on cumulus gws for prod
calico::reflector: true

profile::firewall::rules:
  '020 allow all from transport network to public ip':
    destination: "%{ipaddress_public1}"
    source: '172.18.0.0/19'

profile::base::network::manage_httpproxy: 'true'
profile::base::network::http_proxy:       "%{hiera('service__address__proxy')}:8888"
